# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-07 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citydict',
            old_name='add_times',
            new_name='add_time',
        ),
    ]
