# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 23:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180407_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '\u6559\u5e08', 'verbose_name_plural': '\u6559\u5e08'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='add_time',
            field=models.CharField(default=datetime.datetime.now, max_length=50, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u6559\u5e08\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='\u6240\u5c5e\u673a\u6784'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_company',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6240\u5728\u516c\u53f8'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_years',
            field=models.IntegerField(default=0, verbose_name='\u5de5\u4f5c\u5e74\u9650'),
        ),
    ]
