# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-11 23:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u59d3\u540d')),
                ('tel_num', models.CharField(max_length=11, verbose_name='\u7535\u8bdd')),
                ('course', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6211\u8981\u5b66\u4e60',
                'verbose_name_plural': '\u6211\u8981\u5b66\u4e60',
            },
        ),
    ]
